on: [push, pull_request]
name: check_quality
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -cover ./...
    - name: Build
      run: go build
